CREATE TABLE PAIS (ID_PAIS NUMBER PRIMARY KEY, 
                NM_PAIS VARCHAR2(30) NOT NULL);
    
CREATE TABLE ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                    NM_ESTADO VARCHAR2(30) NOT NULL,
                    ID_PAIS NUMBER);
                    
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY
(ID_ESTADO) REFERENCES PAIS (ID_PAIS); 